# Generated by Django 5.1.1 on 2024-10-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teck_Inventory_Balance_05',
            fields=[
                ('Artículo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripción', models.CharField(max_length=255)),
                ('Stock_total', models.IntegerField()),
                ('Cantidad_reservada', models.IntegerField()),
                ('Cantidad_disponible', models.IntegerField()),
                ('Costo_promedio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Last_PO_Vendor_Date', models.DateField()),
                ('Last_PO_Vendor', models.CharField(max_length=255)),
                ('Quantity_to_buy', models.IntegerField()),
            ],
        ),
    ]
