# Generated by Django 5.1.1 on 2024-10-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teck_Inventory_Balance',
            fields=[
                ('Artículo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripción', models.CharField(max_length=255)),
                ('Stock_total', models.CharField(max_length=255)),
                ('Cantidad_reservada', models.CharField(max_length=255)),
                ('Cantidad_disponible', models.CharField(max_length=255)),
                ('Costo_promedio', models.CharField(max_length=255)),
                ('Last_PO_Number', models.CharField(max_length=255)),
                ('Last_PO_Vendor_Date', models.CharField(max_length=255)),
                ('Last_PO_Vendor', models.CharField(max_length=255)),
                ('Quantity_to_buy', models.CharField(max_length=255)),
            ],
        ),
    ]
