# Generated by Django 5.1.1 on 2024-10-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uploadData', '0002_teck_inventory_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teck_Inventory_Balance_02',
            fields=[
                ('Artículo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripción', models.CharField(max_length=255)),
                ('Stock_total', models.CharField(max_length=255)),
                ('Cantidad_reservada', models.CharField(max_length=255)),
                ('Cantidad_disponible', models.CharField(max_length=255)),
                ('Costo_promedio', models.CharField(max_length=255)),
                ('Last_PO_Vendor', models.CharField(max_length=255)),
                ('Last_PO_Number', models.CharField(max_length=255)),
                ('Last_PO_Vendor_Date', models.CharField(max_length=255)),
                ('Quantity_to_buy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataFromCreatedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_sheet', models.CharField(max_length=255)),
                ('start_cell', models.CharField(max_length=5)),
                ('name_table', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
